# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My GitHub Page
email: blam92@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Testing github pages and jekyll. # the subpath of your site, e.g. /blog
url: "http://blam92.com" # the base hostname & protocol for your site
twitter_username: blam92
github_username:  blam92

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
